server:
  port: 9000

spring:
  application:
    name: ConfigServer

  profiles:
    active: native    # does not use git. application ymls should be in classpath

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
